class dummyData{
  List dummy=[
    {"message_id":1,
    "message":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    "timestamp":1591354516,
    "name":"",
    "isMe":true},
    {"message_id":2,
    "message":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut",
    "timestamp":1591354516,
    "name":"John",
    "isMe":false},
    {"message_id":1,
    "message":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut",
    "timestamp":1591354516,
    "name":"Amy",
    "isMe":false},
    {"message_id":1,
    "message":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut",
    "timestamp":1591354516,
    "name":"",
    "isMe":true},
    {"message_id":1,
    "message":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut",
    "timestamp":1591354516,
    "name":"Chris",
    "isMe":false},
    
  ];
}