language: dart
dist: xenial
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - if [ ! -f $HOME/flutter/bin/flutter ] ; then git clone https://github.com/flutter/flutter.git -b stable ; fi
  - $HOME/flutter/bin/flutter doctor
  - $HOME/flutter/bin/flutter upgrade
  - gem install coveralls-lcov
script:
  - ./flutter/bin/flutter test --coverage
after_success:
  - coveralls-lcov coverage/lcov.info
cache:
  directories:
    - flutter
    - $HOME/.pub-cache
